name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Run Style Checks
        run: npm run lint

      - name: Run Tests
        run: npm test -- --browsers=ChromeHeadless --watch=false
